/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryType' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'address' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'createReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Vec(CartItem), IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryType' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'address' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'createReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [IDL.Opt(Reservation)], ['query']),
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Vec(CartItem), IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };