/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'menuItemId' : bigint }
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'category' : string,
  'isVeg' : boolean,
  'price' : number,
}
export interface Order {
  'id' : bigint,
  'status' : string,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'deliveryType' : string,
  'totalAmount' : number,
  'address' : string,
  'items' : Array<CartItem>,
}
export interface Reservation {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'createdAt' : bigint,
  'time' : string,
  'phone' : string,
  'guests' : bigint,
}
export interface Review {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addReview' : ActorMethod<[string, bigint, string], bigint>,
  'createReservation' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getReservation' : ActorMethod<[bigint], [] | [Reservation]>,
  'getReservations' : ActorMethod<[], Array<Reservation>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'placeOrder' : ActorMethod<
    [Array<CartItem>, string, string, string, number],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];